---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
# https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml
#- https://github.com/knative/serving/releases/download/knative-v1.13.1/serving-crds.yaml
#- https://github.com/knative/serving/releases/download/knative-v1.13.1/serving-core.yaml
- https://github.com/knative/net-kourier/releases/download/knative-v1.13.0/kourier.yaml

patches:
  - path: svc_kourier.yaml


# patches:
#   - target:
#       version: v1
#       kind: Service
#       name: kourier
#     patch: |-
#       - op: replace
#         path: /spec/type
#         value: NodePort
#       - op: replace
#         path: /spec/ports
#         values:
#           - name: http2
#             nodePort: 31993
#             port: 30080
#             protocol: TCP
#             targetPort: 8080
#           - name: https
#             nodePort: 31491
#             port: 443
#             protocol: TCP
#             targetPort: 8443
