---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb
  namespace: metallb-system
spec:
  addresses:
  # docker network inspect -f '{{.IPAM.Config}}' kind
  #   see: https://kind.sigs.k8s.io/docs/user/loadbalancer/
  - 172.24.0.200-172.24.0.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
