---
apiVersion: v1
kind: Service
metadata:
  name: kourier
  namespace: kourier-system
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 31993
      port: 30080
      protocol: TCP
      targetPort: 8080
    - name: https
      nodePort: 31491
      port: 443
      protocol: TCP
      targetPort: 8443
